export const works = [
    {
        link: 'uvusa',
        name: 'UVU Scheduling App',
        images: [
            {
                imageSrc: "../../uvusa_images/computer/filter.svg",
                position: 'justify-end',
                word: 'Filter Capabilities',
                wordDescription: 'The filter component enables instructors to adjust their schedules by applying specific criteria, such as professor names, room numbers, and course titles. Users have the option to reset all filters, clear the current data, and start fresh by manually entering new data or importing an updated CSV file for efficient management.',
                wordPosition: 'md:left-0',
            },
            {
                imageSrc: "../../uvusa_images/computer/import.svg",
                position: 'justify-start',
                word: 'CSV File Import',
                wordDescription: 'This component allows instructors to upload CSV files containing pre-scheduled classes. The system parses the data and displays it within the scheduling table, streamlining the process and saving valuable time by automating the integration of class information.',
                wordPosition: 'md:right-0',
            },
            {
                imageSrc: "../../uvusa_images/computer/add.svg",
                position: 'justify-end',
                word: 'Adding New Schedules',
                wordDescription: 'Instructors can manually create new class schedules using this component by entering details such as course name, professor, and room number. The system also accommodates the addition of custom schedules with flexible class times and days, making it easy to add unique entries for courses and rooms not yet in the system.',
                wordPosition: 'md:left-0',
            },
            {
                imageSrc: "../../uvusa_images/computer/editDelete.svg",
                position: 'justify-start',
                word: 'Schedule Modification',
                wordDescription: 'This component provides a comprehensive overview of all current schedules stored in the database. Instructors can easily modify or delete schedules as needed, with changes reflected in real-time to ensure the most up-to-date information is always available.',
                wordPosition: 'md:right-0',
            },
        ],
        logoImage: "../../uvusa_images/uvu_logo.png",
        year: '2024',
        month: 'April',
        type: 'Web App, Desktop App',
        quickDesc: 'Pre-Scheduling tool for university instructors',
        projDesc: "The UVU Scheduling App is a pre-scheduling tool designed to help Utah Valley University instructors plan, schedule, adjust, and manage upcoming courses, streamlining the scheduling process.",
        projOver: '<p class="mb-2">The UVU Scheduling App is a redevelopment of the existing scheduling system used by Utah Valley University instructors. The legacy software was outdated and led instructors to rely on alternative solutions such as Microsoft Excel and Google Sheets, which were distributed as spreadsheets. This process was inefficient and prone to issues, causing significant administrative headaches and scheduling conflicts.</p><p class="mb-2">After consulting with the scheduling coordinator and the design team, we developed a new solution tailored to address the instructors\' needs and streamline the scheduling process. The updated app incorporates features and improvements that not only meet but exceed the instructors\' expectations, ensuring a more effective and user-friendly scheduling experience.</p>',
        projGoals: '<ul class="list-disc pl-6"><li class="mb-4">Develop a robust app and system for instructors to schedule, manage, and maintain their classes efficiently.</li><li class="mb-4 ">Design an intuitive user interface that is visually appealing, easy to navigate, and accessible.</li><li class="mb-4 ">Incorporate advanced filtering options to enhance usability and streamline the scheduling process.</li><li class="mb-4 ">Enable CSV import functionality for pre-scheduled classes to simplify data integration.</li><li class="mb-4 ">Allow instructors to edit, remove, and add schedule entries seamlessly, ensuring full control over class management.</li><li class="mb-4 ">Provide options for schedule distribution in both digital and printable formats for flexibility.</li></ul>',
        projTech: '<p>Sveltekit</p><p>TypeScript</p><p>Node</p><p>Skeleton UI</p><p>MongoDB</p>',
        projSrcCode: "https://github.com/Andyrooooo/uvuschedulingapp",
        projApp: "https://uvuschedulingapp.vercel.app/",
        mockVid: "../../uvusa_images/uvusa_video2.mp4",
        backOne: "../../uvusa_images/uvu_background1.svg",
        backTwo: "../../uvusa_images/uvu_background2.svg",
        backThree: "../../uvusa_images/uvu_background3.svg",
        backFour: "../../uvusa_images/uvu_background4.svg",
        mobileAndDesk: false,
        projLink: "../../uvusa_link.svg",
        color: 'from-uvusaColorSecond to-uvusaColor'
    },


    {
        link: 'fssa',
        name: 'Fullstack Svelte App',
        images: [
            {
                imageSrc: "../../fssa_images/computer/login.svg", 
                imageSrcMobile: "../../fssa_images/mobile/login.svg",
                position: 'justify-end',
                word: 'OAuth Login',
                wordDescription: 'The OAuth Login feature enables users to securely sign in using their GitHub account, providing a seamless authentication process. A logout option is also available for enhanced security and user convenience.',
                wordPosition: 'md:left-0',

            },
            {
                imageSrc: "../../fssa_images/computer/home.svg", 
                imageSrcMobile: "../../fssa_images/mobile/home.svg",
                position: 'justify-start',
                word: 'Animated Home Page',
                wordDescription: 'After logging in, users are greeted by an animated home page, designed to guide them smoothly through the app’s features and navigation with engaging visual cues.',
                wordPosition: 'md:right-0',

            },
            {
                imageSrc: "../../fssa_images/computer/food.svg", 
                imageSrcMobile: "../../fssa_images/mobile/food.svg",
                position: 'justify-end',
                word: 'Restaurant Search',
                wordDescription: 'The restaurant search feature retrieves all available dining options from the database. Users can apply multiple filters to refine results, making it easy to find the perfect place to eat.',
                wordPosition: 'md:left-0',
            },
            {
                imageSrc: "../../fssa_images/computer/listings.svg",
                imageSrcMobile: "../../fssa_images/mobile/listings.svg", 
                position: 'justify-start',
                word: 'Space Listings',
                wordDescription: 'This feature displays a curated list of spaces from the database. Each listing card includes key details, making it simpler for users to choose the right option.',
                wordPosition: 'md:right-0',
            },
            {
                imageSrc: "../../fssa_images/computer/listings_closer_look.svg", 
                imageSrcMobile: "../../fssa_images/mobile/listings_closer_look.svg",
                position: 'justify-end',
                word: 'Listing Overview',
                wordDescription: 'Upon selecting a listing, users are directed to a detailed view of the space. The first section highlights the listing’s images, offering a visual overview of the space.',
                wordPosition: 'md:left-0',
            },
            {
                imageSrc: "../../fssa_images/computer/listings_closer_look2.svg", 
                imageSrcMobile: "../../fssa_images/mobile/listings_closer_look2.svg",
                position: 'justify-start',
                word: 'Listing Details',
                wordDescription: 'As users scroll through the listing, they can view all relevant details, leading to the option to make a reservation for the space.',
                wordPosition: 'md:right-0',
            },
            {
                imageSrc: "../../fssa_images/computer/reviews.svg", 
                imageSrcMobile: "../../fssa_images/mobile/reviews.svg",
                position: 'justify-end',
                word: 'Listing Reviews',
                wordDescription: 'In the reviews section, users can browse feedback from previous guests, with detailed ratings available to provide deeper insight into the listing’s quality.',
                wordPosition: 'md:left-0',
            },
            {
                imageSrc: "../../fssa_images/computer/write_review.svg", 
                imageSrcMobile: "../../fssa_images/mobile/write_review.svg",
                position: 'justify-start',
                word: 'Write a Review',
                wordDescription: 'Users can contribute their own reviews of the listing, adding to the reviews section to help future guests make informed decisions.',
                wordPosition: 'md:right-0',
            },
            {
                imageSrc: "../../fssa_images/computer/user_profile.svg", 
                imageSrcMobile: "../../fssa_images/mobile/user_profile.svg",
                position: 'justify-end',
                word: 'User Profile',
                wordDescription: 'A user’s profile picture is displayed in the top right corner, providing quick access to personal details such as name, email, and a link to view reservations.',
                wordPosition: 'md:left-0',
            },
            {
                imageSrc: "../../fssa_images/computer/reservations.svg", 
                imageSrcMobile: "../../fssa_images/mobile/reservations.svg",
                position: 'justify-start',
                word: 'Your Reservations',
                wordDescription: 'By selecting the reservations link, users are taken to a page that displays all of their past and upcoming reservations, allowing them to manage bookings with ease.',
                wordPosition: 'md:right-0',
            },
        ],
        image: 'fssa_sm.svg',
        logoImage: "../../fssa_images/fssa_logo4.svg",
        year: '2024',
        month: 'April',
        type: 'Web App',
        quickDesc: 'Property reservation app',
        projDesc: 'Named <a class="text-important">Andrew Kesters Listings</a>, this full-stack app allows users to easily reserve properties, from homes to apartments, with just a click. Additionally, users can explore nearby restaurants, saving time on finding a place to eat. ',
        projOver: '<p class="mb-2">This project was designed to demonstrate my full-stack development skills. Using sample data from MongoDB Atlas, I created an engaging user experience. It builds upon a previous project, the <a class="text-important">Svelte Tutorial App</a>, by adding new features and functionality with the tools and technologies I’ve learned in the DGM program. Throughout this project, I gained valuable insights into server-side logic, routing, database management, and front-end development techniques, all while enjoying the challenge. <a class="text-emerald-200">(Please note that the reservations are for demonstration purposes only and not actual bookings.)</a></p>',
        projGoals: '<ul class="list-disc pl-6"><li class="mb-4">Utilize conditional logic, TypeScript array methods, and front-end framework elements to efficiently render large lists on the web client.</li><li class="mb-4">Leverage the appropriate libraries to build and manage the SvelteKit front-end using a real development toolset.</li><li class="mb-4">Integrate NPM, SvelteKit, and MongoDB to create and manage the back-end of your project.</li><li class="mb-4"><ul><li class="mb-4">Create, use, and manage:</li><li class="mb-4 ml-4">A custom MongoDB data model and API using organized or externally sourced data (e.g., via API call)</li><li class="mb-4 ml-4">An authentication workflow with OAuth and a MongoDB users collection to support signup, login, and logout functionality.</li><li class="mb-4 ml-4">A combination of server pages, API routes, layouts, and page routes in your SvelteKit code.</li><li class="mb-4 ml-4">Routes with cohesive layouts, themes, color schemes, and interactive user experiences.</li><li class="mb-4 ml-4">A front door with authentication and seamless navigation between secure routes.</li><li class="mb-4 ml-4">Route guarding to restrict access to certain routes unless the user is logged in.</li><li class="mb-4 ml-4">UI elements like modals, pop-ups, and toasts with clear dismissal options.</li><li class="mb-4 ml-4">A custom favicon to replace the default Skeleton UI icon.</li></ul></li></ul>',
        projTech: '<p>Sveltekit</p><p>Node</p><p>OAuth</p><p>MongoDB</p>',
        projSrcCode: "https://github.com/Andyrooooo/fullstack_svelte_app",
        projApp: "https://fullstack-svelte-app.vercel.app/",
        backOne: "../../fssa_images/fssa_background1.svg",
        backTwo: "../../fssa_images/fssa_background2.svg",
        backThree: "../../fssa_images/fssa_background3.svg",
        backFour: "../../fssa_images/fssa_background4.svg",
        mockVid: "../../fssa_images/fssa_video_desk2.mp4",
        mockMobileVid: "../../fssa_images/fssa_video_mobile2.mp4",
        mobileAndDesk: true,
        projLink: "../../fssa_link.svg",
        color: 'from-fssaColorSecond to-fssaColor'
    },


    {
        link: 'sta',
        name: 'Svelte Tutorial App',
        images: [
            {
                imageSrc: "../../../sta_images/computer/login.svg", 
                imageSrcMobile: "../../../sta_images/mobile/login.svg",
                position: 'justify-end',
                word: 'OAuth Login',
                wordDescription: 'The OAuth Login feature enables users to securely sign in using their GitHub account, providing a seamless authentication process. A logout option is also available for enhanced security and user convenience.',
                wordPosition: 'md:left-0',
                
            },
            {
                imageSrc: "../../../sta_images/computer/home.svg", 
                imageSrcMobile: "../../../sta_images/mobile/home.svg",
                position: 'justify-start',
                word: 'Home Page',
                wordDescription: 'The home page features a series of buttons, each corresponding to a specific section of the tutorial, allowing users to easily navigate through the content.',
                wordPosition: 'md:right-0',
                
            },
            {
                imageSrc: "../../../sta_images/computer/component.svg", 
                imageSrcMobile: "../../../sta_images/mobile/component.svg",
                position: 'justify-end',
                word: 'Tutrorial Component',
                wordDescription: 'When a section is selected, the tutorial component displays the lesson content, offering users a focused learning experience on that topic.',
                wordPosition: 'md:left-0',
                
            },
            {
                imageSrc: "../../../sta_images/computer/multiple_components.svg", 
                imageSrcMobile: "../../../sta_images/mobile/multiple_components.svg",
                position: 'justify-start',
                word: 'Additional Components',
                wordDescription: 'Users can explore further lessons by selecting additional components, expanding their knowledge as they move through the tutorial.',
                wordPosition: 'md:right-0',
                
            },
            {
                imageSrc: "../../../sta_images/computer/terms.svg", 
                imageSrcMobile: "../../../sta_images/mobile/terms.svg",
                position: 'justify-end',
                word: 'Svelte Terms',
                wordDescription: 'The "Terms" page allows users to browse Svelte-specific terminology, providing a helpful reference for those learning the framework.',
                wordPosition: 'md:left-0',
                
            },
            {
                imageSrc: "../../../sta_images/computer/terms_opened.svg", 
                imageSrcMobile: "../../../sta_images/mobile/terms_opened.svg",
                position: 'justify-start',
                word: 'Terms Overview',
                wordDescription: 'Upon selecting a term, users are presented with a detailed explanation, example implementations from the Svelte tutorial, and a direct link to the official Svelte documentation for further reading.',
                wordPosition: 'md:right-0',
                
            },
            {
                imageSrc: "../../../sta_images/computer/user_profile.svg", 
                imageSrcMobile: "../../../sta_images/mobile/user_profile.svg",
                position: 'justify-end',
                word: 'User Profile',
                wordDescription: 'In the top-right corner, the user’s profile picture is displayed, offering quick access to personal information such as name, email, and a "Log Out" button that returns the user to the login page.',
                wordPosition: 'md:left-0',
                
            }
        ],
        image: 'sta_sm2.svg',
        logoImage: "../../sta_images/sta_logo.svg",
        year: '2023',
        month: 'December',
        type: 'Web App',
        quickDesc: 'App showcasing Svelte.dev tutorial methods and logic.',
        projDesc: 'The Svelte Tutorial App is built from the svelte.dev tutorial, showcasing the basics of Svelte and SvelteKit in easy-to-read components. It also includes a <a class="text-important">terms</a> page for those unfamiliar with Svelte or JavaScript terminology.',
        projOver: '<p class="mb-2">This app covers the entire Svelte tutorial, from the basics in section one to animations in section eleven. Each nested component in the app represents a lesson from the tutorial, demonstrating Svelte\'s capabilities through practical examples. To enhance the learning experience, a <a class="text-important">terms</a> page is included for users who may be less familiar with Svelte. Additionally, OAuth integration provides a streamlined authentication process, allowing users to log in and sign out easily using their GitHub accounts.</p>',
        projGoals: '<ul class="list-disc pl-6"><li class="mb-4">Utilize Svelte\'s components and routing mechanisms to document basic Svelte functionality.</li><li class="mb-4">Organize code effectively using custom components and multiple functional SvelteKit routes.</li><li class="mb-4">Demonstrate user event handling (e.g., click, mouse over) with actionable examples.</li><li class="mb-4">Showcase data binding to UI elements with practical examples.</li><li class="mb-4">Implement lifecycle functions and writable stores to illustrate their use in the app.</li><li class="mb-4">Incorporate motion, animations, and transitions to enhance the user experience.</li><li class="mb-4">Connect to an external API using SvelteKit loading functions and display the retrieved data in the UI.</li><li class="mb-4">Integrate OAuth for user authentication, allowing login via an OAuth provider like GitHub.</li><li class="mb-4">Design and develop major features with a focus on unique implementation and excellent UX/UI design.</li></ul>',
        projTech: '<p>Svlete</p><p>OAuth</p><p>typeScript</p><p>Skeleton UI</p>',
        projSrcCode: "https://github.com/Andyrooooo/DGM3770_Svelte",
        projApp: "https://dgm-3770-svelte.vercel.app/",
        backOne: "../../sta_images/sta_background1.svg",
        backTwo: "../../sta_images/sta_background2.svg",
        backThree: "../../sta_images/sta_background3.svg",
        backFour: "../../sta_images/sta_background4.svg",
        mockVid: "../../sta_images/sta_video_desk.mp4",
        mockMobileVid: "../../sta_images/sta_video_mobile.mp4",
        mobileAndDesk: true,
        projLink: "../../sta_link2.svg",
        color: 'from-staColor to-white'
    },


    {
        link: 'tta',
        name: 'Time Tracker App',
        images: [
            {
                imageSrc: "../../tta_images/computer/tta1.svg", 
                imageSrcMobile: "../../tta_images/mobile/tta1.svg",
                position: 'justify-end',
                word: 'Home Page',
                wordDescription: 'Upon navigating to the home page, users are presented with the core features of the app, including the timer, categories, projects, notes, time entries, entry list, and options to edit entries. This layout provides easy access to key functions for efficient time tracking and management.',
                wordPosition: 'md:left-0',
            },
            {
                imageSrc: "../../tta_images/computer/tta2.svg", 
                imageSrcMobile: "../../tta_images/mobile/tta2.svg",
                position: 'justify-start',
                word: 'Categories',
                wordDescription: 'The categories component enables users to create, edit, and delete categories, allowing for better organization of time entries by grouping tasks under relevant labels.',
                wordPosition: 'md:right-0',
            },
            {
                imageSrc: "../../tta_images/computer/tta3.svg", 
                imageSrcMobile: "../../tta_images/mobile/tta3.svg",
                position: 'justify-end',
                word: 'Projects',
                wordDescription: 'Similar to the categories component, the projects feature allows users to add, modify, and delete projects, helping to track time across different initiatives or clients with ease.',
                wordPosition: 'md:left-0',
            },
            {
                imageSrc: "../../tta_images/computer/tta4.svg", 
                imageSrcMobile: "../../tta_images/mobile/tta4.svg",
                position: 'justify-start',
                word: 'Notes',
                wordDescription: 'The notes component provides users the ability to add, edit, or delete notes, offering a space to capture detailed information related to specific time entries or tasks.',
                wordPosition: 'md:right-0',
            },
            {
                imageSrc: "../../tta_images/computer/tta5.svg", 
                imageSrcMobile: "../../tta_images/mobile/tta5.svg",
                position: 'justify-end',
                word: 'Time Entries',
                wordDescription: 'As the main feature of the Time Tracker App, the time entries component lets users start a timer to log new time entries. Once the timer stops, the entry is added to the entry list, where it can be reviewed. Users can leave the entry details blank or enhance organization by adding descriptions, project types, and category labels for each entry.',
                wordPosition: 'left-0',
            },
            {
                imageSrc: "../../tta_images/computer/tta6.svg", 
                imageSrcMobile: "../../tta_images/mobile/tta6.svg",
                position: 'justify-start',
                word: 'Entry List',
                wordDescription: 'The entry list displays all past time entries, showing details such as project type, category, description, and total allotted time where applicable. Users also have the option to edit or delete entries directly from this list, ensuring flexibility in managing time logs.',
                wordPosition: 'md:right-0',
            },
            {
                imageSrc: "../../tta_images/computer/tta7.svg", 
                imageSrcMobile: "../../tta_images/mobile/tta7.svg",
                position: 'justify-end',
                word: 'Edit Entries',
                wordDescription: 'By clicking the ellipsis button, users can access the edit entries component. This feature allows them to modify details such as description, project type, category, and total allotted time, with changes reflected in real time for accurate tracking.',
                wordPosition: 'md:left-0',
            },
        ],
        image: 'tta_sm.svg',
        logoImage: "../../tta_images/tta_logo.svg",
        year: '2023',
        month: 'December',
        type: 'Web App',
        quickDesc: 'Time tracking app for tasks and projects',
        projDesc: "Built entirely with vanilla JavaScript, the Time Tracker App enables users to monitor the time spent on tasks through a straightforward interface.",
        projOver: '<p class="mb-2">The app features a timer and start button to initiate tracking, with customization options for adding titles, descriptions, and project names for easy identification. Users can modify, remove, or add categories and project names, as well as edit or delete individual tasks. The app provides three key time metrics for each task: <a class="text-important">weekly total time</a>, <a class="text-important">daily total time</a>, and <a class="text-important">task total time</a>, helping users break down their time allocation according to their needs. Additionally, the app includes a note component to help users keep track of important events.</p>',
        projGoals: '<ul class="list-disc pl-6"><li class="mb-4">Implement 15 fully functional features from the end-user’s perspective.</li><li class="mb-4">Develop an API server with comprehensive endpoint functionality:</li><ul><li class="mb-4 ml-4">Create</li><li class="mb-4 ml-4">Read</li><li class="mb-4 ml-4">Update</li><li class="mb-4 ml-4">Delete</li></ul><li class="mb-4">Use vanilla JavaScript for the frontend.</li><li class="mb-4">Ensure the frontend is well-designed.</li></ul>',
        projTech: '<p>JavaScript</p><p>Node</p>',
        projSrcCode: "https://github.com/Andyrooooo/trackerApp",
        projApp: "https://tracker-app-alpha.vercel.app/",
        backOne: "../../tta_images/tta_background1.svg",
        backTwo: "../../tta_images/tta_background2.svg",
        backThree: "../../tta_images/tta_background3.svg",
        backFour: "../../tta_images/tta_background4.svg",
        mockVid: "../../tta_images/tta_video_desk.mp4",
        mockMobileVid: "../../tta_images/tta_video_mobile.mp4",
        mobileAndDesk: true,
        projLink: "../../tta_link.svg",
        color: 'from-ttaColor to-white'
    },


    {
        link: 'nba',
        name: 'Nonsense Blog App',
        images: [
            {
                imageSrc: "../../nba_images/computer/nba1.svg", 
                imageSrcMobile: "../../nba_images/mobile/nba1.svg",
                position: 'justify-end',
                word: 'Home Page',
                wordDescription: 'The home page displays all posts from the database, providing users with a comprehensive view of the available content in the app.',
                wordPosition: 'md:left-0',


            },
            {
                imageSrc: "../../nba_images/computer/nba2.svg", 
                imageSrcMobile: "../../nba_images/mobile/nba2.svg",
                position: 'justify-start',
                word: 'Filter Posts',
                wordDescription: 'Users can filter posts based on various criteria, including name, category, date, title, and the content of the post’s body, making it easier to find specific posts.',
                wordPosition: 'md:right-0',


            },
            {
                imageSrc: "../../nba_images/computer/nba3.svg", 
                imageSrcMobile: "../../nba_images/mobile/nba3.svg",
                position: 'justify-end',
                word: 'New Posts',
                wordDescription: 'This feature allows users to create and add new posts to the app, enabling content generation and engagement within the platform.',
                wordPosition: 'md:left-0',


            },
            {
                imageSrc: "../../nba_images/computer/nba4.svg",
                imageSrcMobile: "../../nba_images/mobile/nba4.svg", 
                position: 'justify-start',
                word: 'Post Overview',
                wordDescription: 'When viewing a post, users can see key details such as the title, date, category, author’s name, and the full content of the post. They can also interact with the post by liking it or leaving a comment to engage with other users.',
                wordPosition: 'md:right-0',


            },
        ],
        image: 'nba_sm.svg',
        logoImage: "../../nba_images/nba_logo.svg",
        year: '2023',
        month: 'April',
        type: 'Web App',
        quickDesc: 'A simple blogging app',
        projDesc: "A Straightforward Blogging App Enabling Users to Create, Edit, and Delete Posts.",
        projOver: '<p class="mb-2">The Nonsense Blog App was developed to test my skills with the React library. It features capabilities for creating, editing, deleting, liking, and commenting on posts. The app also includes persistent data management via an API server.</p>',
        projGoals: '<ul class="list-disc pl-6"><li class="mb-4">Implement 15 fully functional features using JavaScript (excluding HTML or CSS)</li><li class="mb-4">Use React as the library for development.</li><li class="mb-4">Ensure the frontend is well-designed.</li><li class="mb-4">Host the app live with a publicly accessible URL.</li><li class="mb-4">Enable persistent data management through an API server and hosting.</li></ul>',
        projTech: '<p>React</p><p>Glitch</p>',
        projSrcCode: "https://github.com/Andyrooooo/react-blog-project",
        projApp: "https://react-project-blog-dgm3780.netlify.app/",
        backOne: "../../nba_images/nba_background.svg",
        backTwo: "../../nba_images/nba_background2.svg",
        backThree: "../../nba_images/nba_background3.svg",
        backFour: "../../nba_images/nba_background4.svg",
        mockVid: "../../nba_images/nba_video_desk.mp4",
        mockMobileVid: "../../nba_images/nba_video_mobile.mp4",
        mobileAndDesk: true,
        projLink: "../../nba_link.svg",
        color: 'from-nbaColor to-white'
    },


    {
        link: 'vta',
        name: 'Vue Todo App',
        images: [
            {
                imageSrc: "../../vta_images/computer/vta1.svg", 
                imageSrcMobile: "../../vta_images/mobile/vta1.svg",
                position: 'justify-end',
                word: 'Home Page',
                wordDescription: 'The home page of this simple to-do app features an input field and an "Add" button, allowing users to easily create new to-do items. Below the input, users can view their list of existing to-dos.',
                wordPosition: 'md:left-0',

            },
            {
                imageSrc: "../../vta_images/computer/vta2.svg", 
                imageSrcMobile: "../../vta_images/mobile/vta2.svg",
                position: 'justify-start',
                word: 'Modify Todos',
                wordDescription: 'This component lets users manage their to-do items by editing, deleting, or marking them as complete, offering full control over task organization and completion.',
                wordPosition: 'md:right-0',

            },
        ],
        image: 'vta_sm.svg',
        logoImage: "../../vta_images/vta_logo.svg",
        year: '2023',
        month: 'February',
        type: 'Web App',
        quickDesc: 'A Simple Todo App',
        projDesc: "A to-do app that lets users create, edit, delete, and mark tasks as complete.",
        projOver: '<p class="mb-2">The Vue Todo App is a project designed to test my skills with the Vue framework.</p>',
        projGoals: '<ul class="list-disc pl-6"><li class="mb-4">View todos</li><li class="mb-4">Add todos</li><li class="mb-4">Edit todos</li><li class="mb-4">Complete todos</li><li class="mb-4">Delete todos</li></ul>',
        projTech: '<p>Vue</p>',
        projSrcCode: "https://github.com/Andyrooooo/Basic-Vue-App",
        projApp: "https://basic-vue-app-dgm3780.netlify.app/",
        backOne: "../../vta_images/vta_background1.svg",
        backTwo: "../../vta_images/vta_background2.svg",
        backThree: "../../vta_images/vta_background3.svg",
        backFour: "../../vta_images/vta_background4.svg",
        mockVid: "../../vta_images/vta_video_desk.mp4",
        mockMobileVid: "../../vta_images/vta_video_mobile.mp4",
        mobileAndDesk: true,
        projLink: "../../vta_link.svg",
        color: 'from-vtaColor to-white'
    },
]