export const works = [
    {
        link: 'uvusa',
        name: 'UVU Scheduling App',
        images: [
            {imageSrc: "../../uvusa_images/filter.jpg"},
            {imageSrc: "../../uvusa_images/import.jpg"},
            {imageSrc: "../../uvusa_images/add.jpg"},
            {imageSrc: "../../uvusa_images/editDelete.jpg"},
        ],
        logoImage: "../../uvusa_images/uvu_logo.png",
        year: '2024',
        type: 'Web App',
        projDesc: "The UVU Scheduling App is a pre-scheduling tool which allows the Utah Valley University instructors to plan, schedule, change, and distribute upcoming courses for a more streamlined process.",
        projOver: 'The UVU Scheduling App is a rebuild of the current scheduling software used by the UVU instructors. The current software has been in dire need of an upgrade to allow for a better experience for the instructors. The result has left many instructors to rely on alternatives like Microsoft Excel and Google Sheets which are then distributed out in the form of spreadsheets. Those spreadsheets are created by the <a class="text-important">scheduler</a> who is given schedules on a <a class="text-important">requested basis</a> by the instructors via email or in person request. This method is frought with issues that cause many headaches and conflicts. Once I met with the instructor in charge of the scheduling, the design team and I came up with curated solutions that would tackle the needs and wants of the instructors while also including features and components that go beyond their expectations. ',
        projGoals: '<ul class="list-disc pl-6"><li class="mb-1">Develop a new app and system allowing instructors to schedule and maintain their classes</li><li class="mb-1">Achieve a design that is visually straightforward and easy to navigate</li><li class="mb-1">Create filtering options for ease of use </li><li class="mb-1">Create a component to allow CSV imports for pre-scheduled classes</li><li class="mb-1">Allow instructors the ability to edit, remove, and/or add existing data into the schedule builds</li><li class="mb-1">Completed schedules should be able to be distributed by digital or physical copies</li></ul>',
        projTech: '<p>Sveltekit</p><p>TypeScript</p><p>Node</p><p>Skeleton UI</p><p>MongoDB</p>',
        projSrcCode: "https://github.com/Andyrooooo/test_uvu_app",
        projApp: "https://test-uvu-app.vercel.app/",
        vidBack: "../../uvusa_images/uvu_background2.svg",
        mockVid: "../../uvusa_images/uvusaVid2.mp4",
        carBack: "../../uvusa_images/uvu_background3.svg",
        mobileAndDesk: false,
    },


    {
        link: 'fssa',
        name: 'Fullstack Svelte App',
        images: [
            {imageSrc: "../../fssa_images/login.jpg"},
            {imageSrc: "../../fssa_images/home.jpg"},
            {imageSrc: "../../fssa_images/food.jpg"},
            {imageSrc: "../../fssa_images/listings.jpg"},
            {imageSrc: "../../fssa_images/listing_closer_look.jpg"},
            {imageSrc: "../../fssa_images/listing_closer_look2.jpg"},
            {imageSrc: "../../fssa_images/reviews.jpg"},
            {imageSrc: "../../fssa_images/write_review.jpg"},
            {imageSrc: "../../fssa_images/user_profile.jpg"},
            {imageSrc: "../../fssa_images/reservations.jpg"},
        ],
        image: 'fssa_sm.svg',
        logoImage: "../../fssa_images/fssa_logo4.svg",
        year: '2024',
        type: 'Web App',
        projDesc: 'Titled <a class="text-important">Andrew Kesters listings</a>, this app is a fullstack application that allows users to reserve homes, apartments, and everything in between at the touch of a button. While your at it, you can also view nearby restaurants and save time looking for a place to eat.',
        projOver: 'This project was created to showcase my skills in fullstack development and to do so, I used sample data from the MongoDB Atlas database and built an experience around it. The app builds on the a previous project the <a class="text-important">Svelte Tutorial App</a> and adds more features and functionality to it using the tools and technologies I have learned in the DGM program. I Learned a great deal about server side logic, routing, database management, and even some tricks for front-end development that benefitted me greatly from taking on this project while also having an exciting time doing so. <a class="text-important">(Keep in mind the reservations are just to show what could be and are not actual reserverations)</a>',
        projGoals: '<ul class="list-disc pl-6"><li class="mb-1">Effectively use conditional logic, TypeScript array methods, and front-end framework elements to render large lists on the web client.</li><li class="mb-1">Work with the proper libraries to create and manage the SvelteKit front-end portion of your project using a real development toolset.</li><li class="mb-1">Work with NPM, SvelteKit, and MongoDB to create and manage the back-end portion of your project.</li><li class="mb-1"><ul><li class="mb-1">Create, use, and manage:</li><li class="mb-1 ml-4">A custom MongoDB Data Model and associated API using data you have gathered/organized (could be from some external source via API call).</li><li class="mb-1 ml-4">An Authentication workflow using OAuth and a MongoDB users collection to signup, login, and logout users.</li><li class="mb-1 ml-4">A mix of server page, API, layout, and page routes within your SvelteKit code.</li><li class="mb-1 ml-4">Routes with layouts, themes, color schemes, and user interactions that give a great experience.</li><li class="mb-1 ml-4">Create a front door (with ability to Authenticate) and then a way to maneuver and navigate between cohesive routes</li><li class="mb-1 ml-4">Implement route guarding (Can\'t reach certain routes unless logged in)</li><li class="mb-1 ml-4">Any modals, pop ups, toasts or other items brought up in the UI, have an obvious way for the user to get rid of them</li><li class="mb-1 ml-4">Add a favicon that is different than the one that comes with Skeleton UI.</li></ul></li></ul>',
        projTech: '<p>Sveltekit</p><p>Node</p><p>OAuth</p><p>MongoDB</p>',
        projSrcCode: "https://github.com/Andyrooooo/fullstack_svelte_app",
        projApp: "https://fullstack-svelte-app.vercel.app/",
        vidBack: "../../fssa_images/background.jpg",
        mockVid: "../../fssa_images/fssa_video_desk.mp4",
        mockMobileVid: "../../fssa_images/fssa_video_mobile.mp4",
        carBack: "../../fssa_images/background2.svg",
        mobileAndDesk: true,
    },


    {
        link: 'sta',
        name: 'Svelte Tutorial App',
        images: [
            {imageSrc: "../../../sta_images/login.jpg"},
            {imageSrc: "../../../sta_images/home.jpg"},
            {imageSrc: "../../../sta_images/component.jpg"},
            {imageSrc: "../../../sta_images/multiple_components.jpg"},
            {imageSrc: "../../../sta_images/terms.jpg"},
            {imageSrc: "../../../sta_images/terms_opened.jpg"},
            {imageSrc: "../../../sta_images/user_profile.jpg"}
        ],
        image: 'sta_sm2.svg',
        logoImage: "../../sta_images/sta_logo.svg",
        year: '2023',
        type: 'Web App',
        projDesc: 'The Svelte Tutorial App is a product of the svelte.dev tutorial. It showcases all the basics of Svelte/Sveltekit in easy to read components, with an additional <a class="text-important">terms</a> page for those unfamiliar with the Svelte/JavaScript terminology.',
        projOver: 'This app uses section one which starts with the basics over to animations in section eleven of the Svelte tutorial. Every nested component inside each component of the app is a lesson from the tutorial brought to fruition in the form of an example to exibit the capabilites. Going with the theme of a tutorial app I believed it to be appropriate to add a <a class="text-important">terms</a> page for those who aren\'t as familiar with Svelte. Finally, to achieve a more streamlined experience, I integrated OAuth to allow users to login and sign out with an easy to use authentication linked to GitHub.',
        projGoals: '<ul class="list-disc pl-6"><li class="mb-1">Effectively use Svelte\'s components and routing mechanisms to document basic Svelte functionality.</li><li class="mb-1">Properly organize the code using custom components and multiple functional SvelteKit routes.</li><li class="mb-1">Demonstrate multiple examples of captured user events (click, mouse over, etc.) that cause some action to occur.</li><li class="mb-1">Provide examples of data bound to UI elements.</li><li class="mb-1">Utilize lifecycle functions and writable stores with examples to showcase these.</li><li class="mb-1">Use a mix of motion, animations and transitions to enhance some aspects of the project.</li><li class="mb-1">Connect to an outside API using a mix of SvelteKit loading functions and display retrieved data in the UI.</li><li class="mb-1">Use OAuth to allow users of your app to login using an OAuth provider such as GitHub.</li><li class="mb-1">Design and Develop the major features of the app as uniquely as possible and exhibit great UX/UI design. </li></ul>',
        projTech: '<p>Svlete</p><p>OAuth</p><p>typeScript</p><p>Skeleton UI</p>',
        projSrcCode: "https://github.com/Andyrooooo/DGM3770_Svelte",
        projApp: "https://dgm-3770-svelte.vercel.app/",
        vidBack: "../../sta_images/background.jpg",
        mockVid: "../../sta_images/sta_video_desk.mp4",
        mockMobileVid: "../../sta_images/sta_video_mobile.mp4",
        carBack: "../../sta_images/background2.jpg",
        mobileAndDesk: true,
    },


    {
        link: 'tta',
        name: 'Time Tracker App',
        images: [
            {imageSrc: "../../tta_images/tta1.jpg"},
            {imageSrc: "../../tta_images/tta2.jpg"},
            {imageSrc: "../../tta_images/tta3.jpg"},
            {imageSrc: "../../tta_images/tta4.jpg"},
            {imageSrc: "../../tta_images/tta5.jpg"},
            {imageSrc: "../../tta_images/tta6.jpg"},
            {imageSrc: "../../tta_images/tta7.jpg"},
        ],
        image: 'tta_sm.svg',
        logoImage: "../../tta_images/tta_logo.svg",
        year: '2023',
        type: 'Web App',
        projDesc: "Built completely with vanilla JavaScript, the Time Tracker App is a project that allows users to track their time spent on tasks with a simple interface.",
        projOver: 'The app comes equipped with a timer and start button to initiate tracking, this can also be customized by adding a title, description, and/or a project name to be more easily identifiable. These categories and project names can be modified, removed, and even add new ones. Individual tasks can also be modified and deleted at the users discretion. Key notes to identify will concern the three total times that will be available when a task has been created. This is broken down into <a class="text-important">weekly total time</a>, <a class="text-important">daily total time</a>, and <a class="text-important">task total time</a>. This idea allows users to more easily break down their time alloted to each individuals own needs. The final component of the app is the note component which will allow users to stay on top of key events. ',
        projGoals: '<ul class="list-disc pl-6"><li class="mb-1">15 features, from the viewpoint of the enduser, that are fully functional.</li><li class="mb-1">Must have an API Server utilizing all types of endpoints </li><ul><li class="mb-1 ml-4">Create</li><li class="mb-1 ml-4">Read</li><li class="mb-1 ml-4">Update</li><li class="mb-1 ml-4">Delete</li></ul><li class="mb-1">Vanilla JS on the Frontend</li><li class="mb-1">Frontend must be "well designed"</li></ul>',
        projTech: '<p>JavaScript</p><p>Node</p>',
        projSrcCode: "https://github.com/Andyrooooo/trackerApp",
        projApp: "https://tracker-app-alpha.vercel.app/",
        vidBack: "../../tta_images/background.jpg",
        mockVid: "../../tta_images/tta_video_desk.mp4",
        mockMobileVid: "../../tta_images/tta_video_mobile.mp4",
        carBack: "../../tta_images/background2.jpg",
        mobileAndDesk: true,
    },


    {
        link: 'nba',
        name: 'Nonsense Blog App',
        images: [
            {imageSrc: "../../nba_images/nba1.jpg"},
            {imageSrc: "../../nba_images/nba2.jpg"},
            {imageSrc: "../../nba_images/nba3.jpg"},
            {imageSrc: "../../nba_images/nba4.jpg"},
        ],
        image: 'nba_sm.svg',
        logoImage: "../../nba_images/nba_logo.svg",
        year: '2023',
        type: 'Web App',
        projDesc: "A simple blogging app that allows users to create, edit, and delete posts.",
        projOver: 'The Nonsense Blog App is a project that was created to test my skills with the React library. The app allows you to create, edit, delete, like, and comment on posts. It as well comes with persistent data through the use of an API server.',
        projGoals: '<ul class="list-disc pl-6"><li class="mb-1">15 features that require JavaScript (not HTML or CSS) that are fully functional.</li><li class="mb-1">Must use React as the library</li><li class="mb-1">Frontend must be "well designed" </li><li class="mb-1">Must be hosted live with a public URL</li><li class="mb-1">Allow the app to have persistent data through API server/hosting</li></ul>',
        projTech: '<p>React</p><p>Glitch</p>',
        projSrcCode: "https://github.com/Andyrooooo/react-blog-project",
        projApp: "https://react-project-blog-dgm3780.netlify.app/",
        vidBack: "../../nba_images/background.jpg",
        mockVid: "../../nba_images/nba_video_desk.mp4",
        mockMobileVid: "../../nba_images/nba_video_mobile.mp4",
        carBack: "../../nba_images/background2.jpg",
        mobileAndDesk: true,
    },


    {
        link: 'vta',
        name: 'Vue Todo App',
        images: [
            {imageSrc: "../../vta_images/vta1.jpg"},
            {imageSrc: "../../vta_images/vta2.jpg"},
        ],
        image: 'vta_sm.svg',
        logoImage: "../../vta_images/vta_logo.svg",
        year: '2022',
        type: 'Web App',
        projDesc: "A todo app to allow users to create, edit, delete, and complete todos.",
        projOver: 'The Vue Todo app is a project I created to test my abilities with a new framework. ',
        projGoals: '<ul class="list-disc pl-6"><li class="mb-1">User can view the todos</li><li class="mb-1">User can add todos</li><li class="mb-1">User can edit todos</li><li class="mb-1">User can complete todos</li><li class="mb-1">User can delete todos</li></ul>',
        projTech: '<p>Vue</p>',
        projSrcCode: "https://github.com/Andyrooooo/Basic-Vue-App",
        projApp: "https://basic-vue-app-dgm3780.netlify.app/",
        vidBack: "../../vta_images/background.jpg",
        mockVid: "../../vta_images/vta_video_desk.mp4",
        mockMobileVid: "../../vta_images/vta_video_mobile.mp4",
        carBack: "../../vta_images/background2.jpg",
        mobileAndDesk: true,
    },
]